// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcowXBFMb0zQnTMH9qQM3H_fdwzyeFfLk',
    appId: '1:1027586857770:web:1d08fe587c2ec920979c53',
    messagingSenderId: '1027586857770',
    projectId: 'luna-992f8',
    authDomain: 'luna-992f8.firebaseapp.com',
    storageBucket: 'luna-992f8.firebasestorage.app',
    measurementId: 'G-7VREC8EZK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtUcrmwCOpeVHf8oHLRDS3GAIvvP4sj7Y',
    appId: '1:1027586857770:android:2f0ef2abc37c2613979c53',
    messagingSenderId: '1027586857770',
    projectId: 'luna-992f8',
    storageBucket: 'luna-992f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWSpqWHGdnt3Ju8QE-4k1Mfn7sKMBiPFU',
    appId: '1:1027586857770:ios:f871b65bc8511339979c53',
    messagingSenderId: '1027586857770',
    projectId: 'luna-992f8',
    storageBucket: 'luna-992f8.firebasestorage.app',
    iosBundleId: 'com.luna.lunaFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWSpqWHGdnt3Ju8QE-4k1Mfn7sKMBiPFU',
    appId: '1:1027586857770:ios:f871b65bc8511339979c53',
    messagingSenderId: '1027586857770',
    projectId: 'luna-992f8',
    storageBucket: 'luna-992f8.firebasestorage.app',
    iosBundleId: 'com.luna.lunaFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcowXBFMb0zQnTMH9qQM3H_fdwzyeFfLk',
    appId: '1:1027586857770:web:bef338b5716732ce979c53',
    messagingSenderId: '1027586857770',
    projectId: 'luna-992f8',
    authDomain: 'luna-992f8.firebaseapp.com',
    storageBucket: 'luna-992f8.firebasestorage.app',
    measurementId: 'G-WKY1FEZ81Y',
  );
}
